---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/name: Foo
    name: imageuseslatesttag
  spec:
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: Foo
    template:
      metadata:
        labels:
          app.kubernetes.io/name: Foo
      spec:
        containers:
          - name: bar
            image: quay.io/redhat-cop/openshift-applier:latest
