name: Run tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: kyverno
        uses: garethahealy/github-actions/kyverno-cli@kyverno
        with:
          tests: test/kyverno-unittests.sh

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Test against KinD
        run: |
          kyvernocli=$(docker images --filter=label=com.github.actions.name=kyverno-cli --format "{{.Repository}}:{{.Tag}}")
          docker run --rm --network host --workdir /kyvernocli --volume "/home/runner/.kube/":"/root/.kube/" --volume "/home/runner/work/kyverno-validate-blog/kyverno-validate-blog":"/kyvernocli" --entrypoint .github/workflows/tests-entrypoint.sh ${kyvernocli}

      - name: Get pods and events if tests failed
        if: ${{ failure() }}
        run: |
          kubectl get nodes
          kubectl get namespaces
          kubectl get pods --all-namespaces
          kubectl get events --all-namespaces

      - name: Build jenkins agent
        uses: redhat-actions/buildah-build@v2
        with:
          image: jenkins-agent-kyverno
          dockerfiles: |
            ./jenkins/Dockerfile